import type { LootTableDef } from './types';

type E = [string, number, number, number];
function t(id: string, rolls: [number, number], entries: E[], guaranteed?: { itemId: string; qty: [number, number] }[]): LootTableDef {
  return { id, rolls, entries: entries.map(([itemId, weight, a, b]) => ({ itemId, weight, qty: [a, b] })), ...(guaranteed ? { guaranteed } : {}) };
}

/** Loot tables (TUNABLE). Contents are rolled once per raid with the 'loot' stream and never re-rolled. */
export const LOOT_TABLES: LootTableDef[] = [
  t('core.loot.farm_food', [2, 4], [
    ['core.mat.cloth', 20, 1, 3],
    ['core.med.bandage', 10, 1, 2],
    ['core.mat.antiseptic', 5, 1, 1],
    ['core.val.spoon', 6, 1, 1],
    ['core.mat.scrap', 14, 1, 2],
    ['core.mat.metal', 10, 1, 2],
    ['core.mat.powder', 6, 1, 2],
    ['core.ammo.9.fmj', 8, 8, 20],
    ['core.val.watch', 2, 1, 1],
    ['core.med.painkiller', 3, 1, 1],
    ['core.mat.battery', 3, 1, 1],
  ]),
  t('core.loot.medical', [2, 4], [
    ['core.med.bandage', 25, 1, 2],
    ['core.med.firstaid', 10, 1, 1],
    ['core.med.painkiller', 10, 1, 1],
    ['core.mat.antiseptic', 18, 1, 2],
    ['core.mat.cloth', 18, 1, 3],
    ['core.val.sample', 6, 1, 1],
  ]),
  t('core.loot.tools', [2, 4], [
    ['core.mat.scrap', 25, 1, 3],
    ['core.mat.part', 12, 1, 1],
    ['core.mat.metal', 18, 1, 2],
    ['core.mat.wire', 12, 1, 2],
    ['core.tool.repair_kit', 3, 1, 1],
    ['core.mat.battery', 6, 1, 1],
    ['core.mat.chem', 8, 1, 2],
    ['core.mat.powder', 6, 1, 2],
  ]),
  t('core.loot.ammo', [2, 3], [
    ['core.ammo.9.fmj', 14, 15, 30],
    ['core.ammo.45.fmj', 8, 10, 24],
    ['core.ammo.556.fmj', 12, 15, 30],
    ['core.ammo.762r.fmj', 6, 10, 20],
    ['core.ammo.762d.fmj', 4, 5, 15],
    ['core.ammo.12g.buck', 8, 6, 12],
    ['core.ammo.556.ap', 2, 5, 10],
    ['core.ammo.9.hp', 4, 10, 20],
    ['core.ammo.12g.slug', 2, 4, 8],
    ['core.mag.p9', 3, 1, 1],
    ['core.mag.ar556', 3, 1, 1],
    ['core.mag.c556', 2, 1, 1],
  ]),
  t('core.loot.weapons', [1, 3], [
    ['core.weapon.p9', 8, 1, 1],
    ['core.weapon.h45', 4, 1, 1],
    ['core.weapon.sm9', 5, 1, 1],
    ['core.weapon.c556', 5, 1, 1],
    ['core.weapon.sgp', 4, 1, 1],
    ['core.weapon.ar556', 2, 1, 1],
    ['core.weapon.dmr', 1, 1, 1],
    ['core.mag.p9', 5, 1, 1],
    ['core.mag.sm9', 3, 1, 1],
    ['core.armor.vest1', 5, 1, 1],
    ['core.armor.helmet1', 5, 1, 1],
    ['core.armor.vest2', 2, 1, 1],
    ['core.armor.helmet2', 2, 1, 1],
    ['core.att.suppressor', 1, 1, 1],
    ['core.att.compensator', 2, 1, 1],
    ['core.att.grip', 3, 1, 1],
    ['core.att.stock', 3, 1, 1],
  ]),
  t('core.loot.valuables', [1, 3], [
    ['core.val.spoon', 20, 1, 2],
    ['core.val.ring', 6, 1, 1],
    ['core.val.watch', 12, 1, 1],
    ['core.val.lens', 5, 1, 1],
    ['core.val.radio', 6, 1, 1],
    ['core.val.chip', 2, 1, 1],
    ['core.val.market_note', 8, 1, 1],
    ['core.val.sample', 4, 1, 1],
  ]),
  t('core.loot.scrap', [2, 3], [
    ['core.mat.scrap', 40, 1, 3],
    ['core.mat.metal', 20, 1, 2],
    ['core.mat.wire', 10, 1, 2],
    ['core.mat.part', 6, 1, 1],
  ]),
  t('core.loot.military', [2, 4], [
    ['core.ammo.556.fmj', 10, 15, 30],
    ['core.ammo.556.ap', 4, 10, 20],
    ['core.ammo.762r.fmj', 6, 10, 25],
    ['core.ammo.762d.fmj', 4, 5, 15],
    ['core.armor.vest2', 4, 1, 1],
    ['core.armor.helmet2', 4, 1, 1],
    ['core.armor.vest3', 1, 1, 1],
    ['core.armor.helmet3', 1, 1, 1],
    ['core.throw.frag', 6, 1, 1],
    ['core.throw.smoke', 6, 1, 1],
    ['core.throw.flash', 4, 1, 1],
    ['core.med.firstaid', 6, 1, 1],
    ['core.mag.ar556', 5, 1, 1],
    ['core.mag.ar762', 3, 1, 1],
    ['core.att.suppressor', 1, 1, 1],
    ['core.att.compensator', 2, 1, 1],
    ['core.val.lens', 2, 1, 1],
    ['core.val.chip', 2, 1, 1],
    ['core.bag.hiker', 1, 1, 1],
  ]),
  t('core.loot.office', [1, 3], [
    ['core.val.market_note', 10, 1, 1],
    ['core.val.chip', 2, 1, 1],
    ['core.val.watch', 5, 1, 1],
    ['core.val.spoon', 5, 1, 1],
    ['core.mat.battery', 6, 1, 1],
    ['core.mat.wire', 6, 1, 2],
    ['core.acc.feather', 1, 1, 1],
  ]),
  t('core.loot.fridge', [1, 3], [
    ['core.mat.antiseptic', 10, 1, 1],
    ['core.med.painkiller', 6, 1, 1],
    ['core.med.bandage', 8, 1, 2],
    ['core.mat.cloth', 10, 1, 2],
    ['core.val.sample', 5, 1, 1],
  ]),
  t('core.loot.relief', [1, 2], [
    ['core.med.bandage', 20, 1, 2],
    ['core.mat.cloth', 10, 1, 2],
    ['core.med.firstaid', 5, 1, 1],
  ]),
  t('core.loot.pump_crate', [2, 3], [
    ['core.mat.part', 30, 1, 2],
    ['core.mat.wire', 20, 1, 3],
    ['core.mat.power_unit', 3, 1, 1],
    ['core.mat.battery', 10, 1, 1],
    ['core.tool.repair_kit', 6, 1, 1],
    ['core.att.suppressor', 2, 1, 1],
  ]),
  t('core.loot.signal_rescue', [3, 4], [
    ['core.med.firstaid', 20, 1, 1],
    ['core.throw.frag', 10, 1, 1],
    ['core.ammo.556.ap', 8, 10, 20],
    ['core.armor.vest2', 6, 1, 1],
    ['core.armor.helmet2', 6, 1, 1],
    ['core.val.ring', 8, 1, 1],
    ['core.val.lens', 6, 1, 1],
    ['core.val.chip', 4, 1, 1],
  ]),
  t('core.loot.signal_trap', [1, 2], [
    ['core.mat.scrap', 30, 1, 2],
    ['core.mat.cloth', 20, 1, 2],
    ['core.med.bandage', 10, 1, 1],
  ]),
  t('core.loot.cart', [3, 4], [
    ['core.ammo.762r.fmj', 10, 15, 25],
    ['core.ammo.762d.ap', 5, 5, 10],
    ['core.mag.ar762', 4, 1, 1],
    ['core.mag.dmr', 3, 1, 1],
    ['core.armor.vest3', 2, 1, 1],
    ['core.att.suppressor', 2, 1, 1],
    ['core.val.chip', 4, 1, 1],
    ['core.val.lens', 5, 1, 1],
    ['core.mat.fuel', 3, 1, 1],
    ['core.mat.power_unit', 2, 1, 1],
  ]),
  t('core.loot.freight', [2, 4], [
    ['core.mat.fuel', 6, 1, 1],
    ['core.mat.part', 12, 1, 2],
    ['core.mat.wire', 10, 1, 2],
    ['core.ammo.556.fmj', 8, 15, 30],
    ['core.ammo.762d.fmj', 6, 8, 15],
    ['core.ammo.556.ap', 3, 8, 15],
    ['core.val.market_note', 6, 1, 1],
    ['core.val.chip', 3, 1, 1],
    ['core.mag.dmr', 2, 1, 1],
    ['core.mag.lmg', 1, 1, 1],
    ['core.weapon.bolt', 1, 1, 1],
    ['core.weapon.lmg', 1, 1, 1],
    ['core.weapon.sga', 1, 1, 1],
    ['core.weapon.sm45', 1, 1, 1],
    ['core.weapon.ar762', 1, 1, 1],
    ['core.bag.military', 1, 1, 1],
    ['core.acc.nvg', 1, 1, 1],
  ]),
  // Tutorial crate: no random rolls; its fixed contents are the map container's guaranteed items.
  t('core.loot.tutorial', [0, 0], [['core.med.bandage', 1, 1, 1]]),
  t('core.loot.pocket_basic', [0, 2], [
    ['core.med.bandage', 20, 1, 1],
    ['core.mat.cloth', 15, 1, 2],
    ['core.val.spoon', 8, 1, 1],
    ['core.val.watch', 4, 1, 1],
    ['core.mat.scrap', 15, 1, 1],
    ['core.mat.metal', 10, 1, 1],
    ['core.mat.powder', 8, 1, 1],
    ['core.med.painkiller', 5, 1, 1],
    ['core.val.market_note', 3, 1, 1],
    ['core.mat.battery', 4, 1, 1],
  ]),
  t('core.loot.pocket_marksman', [1, 2], [
    ['core.val.lens', 6, 1, 1],
    ['core.ammo.762d.fmj', 10, 5, 10],
    ['core.med.bandage', 10, 1, 1],
    ['core.val.watch', 4, 1, 1],
  ]),
  t('core.loot.pocket_boss', [3, 4], [
    ['core.val.ring', 10, 1, 1],
    ['core.val.chip', 10, 1, 1],
    ['core.val.lens', 10, 1, 1],
    ['core.ammo.762r.ap', 6, 10, 20],
  ]),
];
