/** Localized strings for maps, regions, interiors, POIs and exits. */
export const mapStrings: Record<string, string> = {
  'map.quarantine_main.name': '격리구역 본토',
  'map.quarantine_main.desc': '버려진 농장, 수풀 수로, 무너진 검문소, 폐쇄 산업 시설. 무료 탈출 2곳(서쪽 배수로·동쪽 도로 끝)과 조건부 탈출 2곳.',
  'map.outer_supply_route.name': '외곽 보급로',
  'map.outer_supply_route.desc': '폐선 화물역과 침엽림 보급창. 사선이 길고 탈출구가 적다. 밤과 악천후가 잦다.',
  'region.farm': '버려진 농장',
  'region.canal': '수풀 수로',
  'region.checkpoint': '무너진 검문소',
  'region.industrial': '폐쇄 산업 시설',
  'region.freight_station': '폐선 화물역',
  'region.conifer_depot': '침엽림 보급창',
  'interior.farm_warehouse': '농장 창고',
  'interior.pump_room': '수로 펌프실',
  'interior.control_room': '산업 시설 통제실',
  'interior.cargo_warehouse': '폐쇄 화물창고',
  'interior.farmhouse': '농가',
  'interior.barn': '헛간',
  'interior.shed': '무너진 창고',
  'interior.checkpoint': '검문소 초소',
  'interior.factory_hall': '공장 본관',
  'interior.storage_shed': '북서 보관 창고',
  'interior.station': '화물역 역사',
  'poi.water_tower': '기울어진 급수탑',
  'poi.red_pump': '붉은 배수 펌프',
  'poi.watchtower': '검문소 감시탑',
  'poi.industrial_yard': '산업 시설 야적장',
  'poi.farmhouse': '농가',
  'poi.checkpoint': '검문소',
  'poi.factory': '공장 본관',
  'poi.freight_station': '화물역 선로',
  'poi.depot': '보급창',
  'poi.forest_cache': '숲속 은닉처',
  'exit.west_drain': '서쪽 배수로',
  'exit.east_road': '동쪽 도로 끝',
  'exit.checkpoint_barrier': '검문소 차단기 (통행료 300cr)',
  'exit.freight_elevator': '화물 승강기 (전력 필요)',
  'exit.rail_tunnel': '선로 끝 터널',
  'exit.supply_truck': '보급창 수송 트럭 (연료통 필요)',
  'exit.hint.fee': '계정에서 300cr를 지불하고 차단기를 올린다',
  'exit.hint.power': '발전기를 복구해야 승강기가 움직인다',
  'exit.hint.fuel': '연료통 1개를 소모한다',
  'event.pump.interact': '펌프 재가동 스위치',
  'note.read': '기록 읽기',
};
